export const CURRENCIES = [
  { symbol: "₺", name: "Turkish Lira" },
  { symbol: "$", name: "US Dollar" },
  { symbol: "€", name: "Euro" },
  { symbol: "£", name: "British Pound" },
  { symbol: "¥", name: "Japanese Yen" },
  { symbol: "₹", name: "Indian Rupee" },
  { symbol: "₽", name: "Russian Ruble" },
  { symbol: "₩", name: "Korean Won" },
  { symbol: "A$", name: "Australian Dollar" },
  { symbol: "C$", name: "Canadian Dollar" },
  { symbol: "CHF", name: "Swiss Franc" },
  { symbol: "¥CN", name: "Chinese Yuan" },
  { symbol: "R$", name: "Brazilian Real" },
  { symbol: "R", name: "South African Rand" },
  { symbol: "kr", name: "Swedish Krona" },
  { symbol: "₴", name: "Ukrainian Hryvnia" },
  { symbol: "₱", name: "Philippine Peso" },
  { symbol: "RM", name: "Malaysian Ringgit" },
  { symbol: "₦", name: "Nigerian Naira" },
  { symbol: "₸", name: "Kazakhstani Tenge" },
];
